import { useEffect, useState } from 'react';
import { Plus, Save, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { settingsAPI, type EventClassificationRule } from '../services/api';
import { useTheme } from '../contexts/ThemeContext';

const blank = (): EventClassificationRule => ({ id: `rule-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`, name: '', pattern: '', field: 'message', mode: 'contains', event_type: '', severity: 'warning', enabled: true });

export default function EventClassificationPage() {
  const { c } = useTheme(); const [rules, setRules] = useState<EventClassificationRule[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { settingsAPI.eventClassificationRules().then(r => setRules(r.rules)).catch(e => toast.error(e.message)); }, []);
  const update = (index: number, patch: Partial<EventClassificationRule>) => setRules(prev => prev.map((rule, i) => i === index ? { ...rule, ...patch } : rule));
  const save = async () => { setSaving(true); try { const result = await settingsAPI.updateEventClassificationRules(rules); setRules(result.rules); toast.success('Reglas guardadas'); } catch (e: any) { toast.error(e.message); } finally { setSaving(false); } };
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold" style={{ color: c.textPrimary }}>Clasificación de Eventos</h1><p className="text-sm" style={{ color: c.textMuted }}>Convertí eventos no clasificados en nombres claros para Monitor, popup, historial y Telegram. Las reglas se aplican a eventos nuevos.</p></div><div className="space-y-3">{rules.map((rule, index) => <div key={rule.id} className="card grid grid-cols-1 md:grid-cols-7 gap-2 items-center"><input value={rule.name} onChange={e => update(index, { name: e.target.value })} placeholder="Nombre de regla" className="input" /><input value={rule.pattern} onChange={e => update(index, { pattern: e.target.value })} placeholder="Texto a detectar" className="input" /><select value={rule.field} onChange={e => update(index, { field: e.target.value as EventClassificationRule['field'] })} className="input"><option value="message">Mensaje</option><option value="topics">Topics</option><option value="any">Ambos</option></select><input value={rule.event_type} onChange={e => update(index, { event_type: e.target.value.replace(/\s+/g, '_').toLowerCase() })} placeholder="Nombre mostrado" className="input" /><select value={rule.severity} onChange={e => update(index, { severity: e.target.value as EventClassificationRule['severity'] })} className="input"><option value="critical">Crítico</option><option value="warning">Warning</option><option value="info">Info</option></select><label className="text-xs flex gap-2 items-center"><input type="checkbox" checked={rule.enabled} onChange={e => update(index, { enabled: e.target.checked })} />Activa</label><button onClick={() => setRules(prev => prev.filter((_, i) => i !== index))} className="btn-secondary"><Trash2 className="w-4 h-4" /></button></div>)}</div><div className="flex gap-2"><button onClick={() => setRules(prev => [...prev, blank()])} className="btn-secondary"><Plus className="w-4 h-4 inline mr-1" />Agregar regla</button><button disabled={saving} onClick={save} className="btn-primary"><Save className="w-4 h-4 inline mr-1" />Guardar</button></div><div className="card text-sm" style={{ color: c.textSecondary }}>Ejemplo para Summer Tower: patrón <code>Detected conflict by ARP response</code>, nombre mostrado <code>conflicto_arp</code>, severidad <b>warning</b>.</div></div>;
}
